name: Eszentrium
main: esze.main.main
version: 1.0
author: [Philipp0002, adermake, Astromake]
api-version: 1.13
    
commands:
  spell:
    description: Make more SPELLS!!
    usage: spell [name]
  game:
    description: Game management
    usage: 
  maps:
    description: Arena overview
    usage: 
  itemname:
    description: Change name of held item
    usage: 
  setspawn:
    description: Set a spawn
    usage: 
  removemap:
    description: Remove an arena
    usage: 
  setlobby:
    description: Set spawnlocation
    usage: 
  setmode:
    description: Set the gamemode
    usage: 
  setitem:
    description: Set the gamemode
    usage: 
  downloadfile:
    description: Download a file
    usage: 
  ping:
    description: Ping
    usage: 